import type { Metadata } from "next";
import Link from "next/link";
import { SiteShell } from "@/components/SiteChrome";
import { PagePortrait } from "@/components/AnimatedVisuals";
import { getPublishedCourses } from "@/lib/lms";

export const metadata: Metadata = { title: "Online Courses & Free eBooks", description: "Learn digital marketing, Meta Ads, Office and AI with lessons, quizzes and certificates.", alternates: { canonical: "/courses" } };
const books = [["Digital Marketing Playbook","/ebooks/digital-marketing-growth-playbook.pdf"],["Meta Ads Blueprint","/ebooks/meta-ads-lead-generation-blueprint.pdf"],["Microsoft Word Essentials","/ebooks/microsoft-word-essentials.pdf"],["Microsoft Excel Essentials","/ebooks/microsoft-excel-essentials.pdf"],["PowerPoint Essentials","/ebooks/microsoft-powerpoint-essentials.pdf"],["AI Tools for Business","/ebooks/ai-tools-for-work-and-business.pdf"],["How to Use AI","/ebooks/how-to-use-ai-practical-guide.pdf"]];

export default async function CoursesPage() { const list = await getPublishedCourses(); return <SiteShell><main>
  <section className="page-hero visual-page-hero"><div className="container page-hero-split"><div><p className="eyebrow">MyDigitalSkills Courses</p><h1>Learn skills. Pass the quiz. <span>Earn a certificate.</span></h1><p>One learning hub for free and paid courses, section-wise lessons, videos, eBooks, assessments and verified certificates.</p><div className="hero-actions"><a className="button button-primary" href="#catalogue">Explore Courses →</a><a className="button button-light" href="/student/dashboard">Student Dashboard</a></div></div><PagePortrait pose="pointing"/></div></section>
  <section className="section" id="catalogue"><div className="container"><div className="section-heading"><div><p className="eyebrow">Course catalogue</p><h2>Choose your <span className="red-text">next skill.</span></h2></div><p>Free courses enroll instantly. Paid courses activate after payment confirmation.</p></div><div className="academy-grid">{list.map((course) => <article className="academy-card" key={course.id}><Link className="academy-cover" href={`/courses/${course.slug}`}><img src={course.coverImage || "/images/learning-digital-skills.webp"} alt={course.title} width="1400" height="788" /></Link><div className="academy-body"><div className="course-top"><span className="course-badge">{course.level}</span><strong>{course.priceInr === 0 ? "FREE" : `₹${course.priceInr.toLocaleString("en-IN")}`}</strong></div><h2>{course.title}</h2><p>{course.description}</p><div className="lms-tags"><span>Sections</span><span>Quiz</span><span>{course.priceInr === 0 ? "Free Certificate" : "Premium Certificate"}</span></div><Link className="button button-primary" href={`/courses/${course.slug}`}>{course.priceInr === 0 ? "Enroll Free →" : "View Course →"}</Link></div></article>)}</div></div></section>
  <section className="section section-dark"><div className="container"><div className="section-heading"><div><p className="eyebrow">Free resources</p><h2>Practical <span className="red-text">eBooks.</span></h2></div></div><div className="learning-grid">{books.map(([title,href]) => <article className="learning-card" key={title}><div className="learning-icon">PDF</div><span className="course-badge">FREE EBOOK</span><h3>{title}</h3><p>Step-by-step learning, examples and practice checklist.</p><a className="button button-primary" href={href} download>Download PDF →</a></article>)}</div></div></section>
</main></SiteShell>; }
