"use client";

import { FormEvent, useEffect, useState } from "react";

declare global { interface Window { fbq?: (...args: unknown[]) => void; gtag?: (...args: unknown[]) => void } }
function track(event:string,params:Record<string,string>={}){window.fbq?.("trackCustom",event,params);window.gtag?.("event",event,params)}

export function QuicklyMediaTracker(){
  useEffect(()=>{track("ViewContent",{page:"quicklymedia_hospitality_growth"});const root=document.querySelector<HTMLElement>(".qm-lp");if(!root)return;const targets=root.querySelectorAll<HTMLElement>(".qm-reveal, .qm-section h2, .qm-service, .qm-problem, .qm-case, .qm-package, .qm-step, .qm-channel");targets.forEach((target,index)=>{target.classList.add("qm-motion");target.style.setProperty("--qm-delay",`${Math.min(index%5,4)*65}ms`)});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("qm-visible");observer.unobserve(entry.target)}}),{rootMargin:"0px 0px -7%",threshold:.1});targets.forEach(target=>observer.observe(target));let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-window.innerHeight;root.style.setProperty("--qm-progress",`${max>0?(window.scrollY/max)*100:0}%`)})};update();window.addEventListener("scroll",update,{passive:true});return()=>{observer.disconnect();window.removeEventListener("scroll",update);cancelAnimationFrame(frame)}},[]);
  return <div className="qm-progress" aria-hidden="true"/>;
}

export function QuicklyMediaWhatsApp({className="",placement,children}:{className?:string;placement:string;children:React.ReactNode}){
  const text="Hi Lambodar, I want to grow my restaurant/cafe/lounge business. Please share details about the QuicklyMedia hospitality growth solution.";
  return <a className={className} href={`https://wa.me/918128729003?text=${encodeURIComponent(text)}`} target="_blank" rel="noreferrer" onClick={()=>track("WhatsApp_Click",{page:"quicklymedia",placement})}>{children}</a>
}

export function QuicklyMediaLeadForm(){
  const[saving,setSaving]=useState(false),[error,setError]=useState(""),[started,setStarted]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),challenge=String(data.get("challenge")||"Need complete growth strategy");setSaving(true);setError("");const payload={name:data.get("name"),phone:data.get("phone"),email:"",business:`${data.get("business")} · ${data.get("category")} · ${data.get("city")}`,service:`QuicklyMedia — ${challenge}`,source:"quicklymedia-hospitality-landing-page",message:`Instagram / Google: ${data.get("presence")||"Not supplied"} | Challenge: ${challenge}`};try{const response=await fetch("/api/admin/enquiries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error()}catch{setError("Details save nahi ho paaye. Please WhatsApp button se direct connect karein.");setSaving(false);return}track("Lead",{source:"quicklymedia_form",challenge});track("Form_Submit",{source:"quicklymedia_form"});const message=`Hi Lambodar, I submitted my QuicklyMedia hospitality growth audit request.\n\nName: ${data.get("name")}\nBusiness: ${data.get("business")}\nCity: ${data.get("city")}\nBusiness Type: ${data.get("category")}\nChallenge: ${challenge}`;setSaving(false);window.open(`https://wa.me/918128729003?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")}
  return <form className="qm-form" onSubmit={submit} onFocus={()=>{if(!started){setStarted(true);track("Form_Start",{source:"quicklymedia_form"})}}}><p className="qm-kicker">FREE · NO OBLIGATION</p><h2>Let’s analyse your hospitality business.</h2><p>Share the basics. Your request will be saved securely and continued on WhatsApp.</p><div className="qm-form-grid"><label><span>Your Name *</span><input name="name" required autoComplete="name" placeholder="Full name"/></label><label><span>Business Name *</span><input name="business" required placeholder="Restaurant / brand"/></label><label><span>Phone / WhatsApp *</span><input name="phone" required inputMode="tel" autoComplete="tel" placeholder="WhatsApp number"/></label><label><span>City *</span><input name="city" required placeholder="Business location"/></label><label><span>Business Type *</span><select name="category" required defaultValue=""><option value="" disabled>Select business type</option><option>Restaurant</option><option>Cafe</option><option>Lounge</option><option>Club</option><option>Bar</option><option>Banquet</option><option>Cloud Kitchen</option><option>Hotel / Resort</option></select></label><label><span>Biggest Challenge *</span><select name="challenge" required defaultValue=""><option value="" disabled>Select challenge</option><option>Need More Footfall</option><option>Need More Reservations</option><option>Meta Ads Not Working</option><option>Google Visibility</option><option>Social Media Growth</option><option>Swiggy / Zomato Growth</option><option>Events & Offers Promotion</option><option>WhatsApp / CRM Automation</option><option>Need Complete Growth Strategy</option></select></label><label className="full"><span>Instagram / Google Link (Optional)</span><input name="presence" placeholder="Profile link or username"/></label></div>{error&&<p className="qm-form-error">{error}</p>}<button className="qm-button qm-button-primary qm-submit" type="submit" disabled={saving}>{saving?"SUBMITTING…":"GET MY FREE GROWTH AUDIT →"}</button><small>Direct consultation · Private information · No obligation</small></form>
}
