import type{Metadata}from"next";
import{QuicklyMediaLeadForm,QuicklyMediaTracker,QuicklyMediaWhatsApp}from"@/components/QuicklyMediaLeadForm";

export const metadata:Metadata={title:"QuicklyMedia | Restaurant, Cafe & Hospitality Growth Marketing",description:"QuicklyMedia helps restaurants, cafes, lounges, clubs, bars and banquets grow through social media, Meta Ads, Google, Swiggy, Zomato, reservations and automation.",alternates:{canonical:"/quicklymedia"},openGraph:{title:"QuicklyMedia — One-Stop Hospitality Growth Solution",description:"Strategy, content, ads, local visibility, reservations and automation for hospitality businesses.",type:"website",images:[{url:"/images/growth/lambodar-hospitality.jpg",alt:"Lambodar Patra — Hospitality Growth Consultant"}]}};

const problems=[["↘","Low weekday footfall"],["▣","Not getting table bookings"],["₹","Ads running, no results"],["G","Poor Google visibility"],["#","Social media not growing"],["★","Events not getting response"],["⚡","Aggregator sales are low"],["↻","Enquiry follow-up is missed"]];
const channels=["Instagram","Facebook","Meta Ads","Google Business","Google Ads","WhatsApp","Website","Table Booking","Swiggy","Zomato","Magicpin","Dineout","EazyDiner","Reviews","CRM & Automation"];
const services=[["01","Social Media & Branding","Facebook and Instagram management · Content strategy · Creative design · Reels · Brand positioning · Campaign planning"],["02","Performance Marketing","Meta Ads · Google Ads · Lead generation · Retargeting · Reservation campaigns · Event promotion"],["03","Google & Local Growth","Google Business Profile · Local SEO · Reviews · Search visibility · Maps actions · Offer and event updates"],["04","Delivery & Aggregators","Swiggy · Zomato · Magicpin · Dineout · EazyDiner · Listing setup · Menu and offer visibility"],["05","Website & Reservations","Restaurant website · Digital menu · Table booking · Party enquiry · Landing pages · Conversion tracking"],["06","CRM & Automation","WhatsApp enquiry flow · Lead status · Follow-up reminders · Booking data · Review requests · Reporting"]];
const projects=[["Carnivale Food Delights","Hospitality marketing, offers and digital visibility."],["Spicy Vibe","Social media and hospitality marketing support · Crossings Republik, Ghaziabad."],["Moire Air Lounge & Bar","Events, offers, booking enquiries and digital promotion."],["The Flavor Express","Restaurant visibility and marketing support."],["Chaat Di Hatti","Local food brand communication and promotion."],["Kimaya Foods & Caterers","Food and catering business digital support."]];
const faqs=[["Can you help a newly opened restaurant or cafe?","Yes. We can build the digital foundation, profile positioning, content direction, local visibility and launch campaigns around the business objective."],["Do you only handle social media?","No. QuicklyMedia connects social media with Google, Meta Ads, aggregators, websites, reservations, WhatsApp, CRM and follow-up."],["Can you manage Swiggy, Zomato and other platforms?","Support can include listing review, setup guidance, menu and offer visibility, image direction and platform-performance monitoring."],["Is advertising budget included in the monthly fee?","No. Meta Ads, Google Ads and aggregator promotional budgets are paid separately by the business."],["Is a content shoot included?","The monthly hospitality package can include one planned interior and content shoot, subject to location and finalized scope."],["How does the free audit work?","Submit your business details. Lambodar reviews your visible digital presence, discusses the current challenge and recommends the strongest next move."],["What are the payment terms?","Monthly management starts after final scope confirmation. One month advance is required and platform or advertising budgets remain separate."],["Do you work outside Noida?","Yes. Strategy, campaigns, platform management and reporting can support hospitality businesses across India. Shoot logistics depend on location."]];

export default function QuicklyMediaPage(){const schema={"@context":"https://schema.org","@type":"ProfessionalService",name:"QuicklyMedia",description:"Hospitality growth and digital marketing support for restaurants, cafes, lounges, clubs, bars and banquets.",url:"https://mydigitalskills.in/quicklymedia",telephone:"+918128729003",areaServed:"India",founder:{"@type":"Person",name:"Lambodar Patra",jobTitle:"Hospitality Growth & Digital Marketing Consultant"},serviceType:["Restaurant Marketing","Social Media Marketing","Meta Ads","Google Business Profile","Hospitality Automation"]};return <main className="qm-lp" id="qm-top"><QuicklyMediaTracker/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <header className="qm-nav"><a className="qm-brand" href="#qm-top"><span>QUICKLY</span><b>MEDIA</b><small>Social Media Solutions for Hospitality</small></a><nav><a href="#qm-services">Services</a><a href="#qm-work">Our Work</a><a href="#qm-packages">Packages</a></nav><QuicklyMediaWhatsApp className="qm-nav-cta" placement="header">WhatsApp Us</QuicklyMediaWhatsApp></header>

  <section className="qm-hero"><div className="qm-container qm-hero-grid"><div className="qm-hero-copy"><p className="qm-kicker">RESTAURANT · CAFE · LOUNGE · CLUB · BAR · BANQUET</p><h1>GROW YOUR <em>HOSPITALITY BUSINESS</em> WITH ME.</h1><h2>Your one-stop hospitality growth solution.</h2><p>From Instagram, Facebook and Google to Swiggy, Zomato, reservations and automation—build one connected system that supports visibility, enquiries, footfall and repeat customers.</p><div className="qm-actions"><a className="qm-button qm-button-primary" href="#qm-audit">GET FREE GROWTH AUDIT →</a><QuicklyMediaWhatsApp className="qm-button qm-button-whatsapp" placement="hero">TALK ON WHATSAPP →</QuicklyMediaWhatsApp></div><div className="qm-trust"><span><b>8+</b> Years Experience</span><span>Hospitality Experience</span><span>Strategy to Execution</span><span>Direct Consultation</span></div></div><div className="qm-hero-visual"><div className="qm-photo-glow"/><img src="/images/growth/lambodar-hospitality.jpg" alt="Lambodar Patra, Hospitality Growth Consultant" width="1536" height="1536" fetchPriority="high"/><span className="qm-float one">RESERVATIONS <b>↗</b></span><span className="qm-float two">LOCAL FOOTFALL <b>●</b></span><span className="qm-float three">REPEAT CUSTOMERS <b>↻</b></span></div></div></section>

  <section className="qm-proof-strip"><div className="qm-container">{["Strategy That Works","Content That Connects","Ads That Convert","Growth That Lasts"].map(x=><span key={x}>✦ {x}</span>)}</div></section>

  <section className="qm-section qm-problems"><div className="qm-container"><div className="qm-heading qm-reveal"><p className="qm-kicker">DOES THIS SOUND FAMILIAR?</p><h2>WHAT IS STOPPING <em>YOUR GROWTH?</em></h2><p>Hospitality marketing works when the real business problem is identified first.</p></div><div className="qm-problem-grid">{problems.map(([icon,title])=><article className="qm-problem" key={title}><i>{icon}</i><strong>{title}?</strong><span>+</span></article>)}</div><div className="qm-center-cta"><strong>If you said YES to even one, let’s review your business.</strong><a className="qm-button qm-button-primary" href="#qm-audit">ANALYSE MY RESTAURANT →</a></div></div></section>

  <section className="qm-section qm-ecosystem"><div className="qm-container"><div className="qm-heading centered qm-reveal"><p className="qm-kicker">ONE CONNECTED SYSTEM</p><h2>EVERY HOSPITALITY <em>GROWTH CHANNEL.</em></h2><p>Not separate accounts—one customer journey working under one roof.</p></div><div className="qm-map"><div className="qm-map-core"><img src="/images/growth/lambodar-social-story.png" alt="QuicklyMedia hospitality growth strategy" loading="lazy"/><strong>YOUR VENUE</strong><small>Growth System</small></div><div className="qm-channel-grid">{channels.map((x,i)=><span className={`qm-channel c${i+1}`} key={x}>{x}</span>)}</div></div></div></section>

  <section className="qm-section qm-dark"><div className="qm-container qm-split"><div className="qm-reveal"><p className="qm-kicker">THE GROWTH JOURNEY</p><h2>FROM DISCOVERY TO <em>REPEAT CUSTOMER.</em></h2><p>Likes and followers are not the final goal. The system should help people discover the venue, enquire, reserve, visit, review and return.</p><img className="qm-section-photo" src="/images/growth/lambodar-office.png" alt="Lambodar Patra planning a hospitality marketing system" loading="lazy"/></div><div className="qm-funnel">{["Discovery","Profile Visit","Offer","Enquiry","Reservation","Visit","Review","Repeat Customer"].map((x,i)=><div style={{"--qm-i":i} as React.CSSProperties} key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong><i>↓</i></div>)}</div></div></section>

  <section className="qm-section" id="qm-services"><div className="qm-container"><div className="qm-heading qm-reveal"><p className="qm-kicker">ALL UNDER ONE ROOF</p><h2>COMPLETE HOSPITALITY <em>GROWTH SUPPORT.</em></h2></div><div className="qm-services">{services.map(([no,title,copy])=><article className="qm-service" key={title}><span>{no}</span><h3>{title}</h3><p>{copy}</p><i>↗</i></article>)}</div></div></section>

  <section className="qm-section qm-work" id="qm-work"><div className="qm-container"><div className="qm-heading qm-reveal"><p className="qm-kicker">REAL HOSPITALITY EXPERIENCE</p><h2>BUSINESSES I HAVE <em>SUPPORTED.</em></h2><p>Verified project names are shown without fabricated sales, reach or performance claims.</p></div><div className="qm-cases">{projects.map(([name,work],i)=><article className="qm-case" key={name}><span>{String(i+1).padStart(2,"0")}</span><h3>{name}</h3><p>{work}</p><details><summary>View approach →</summary><p>Business review → Offer and channel strategy → Creative and campaign execution → Enquiry and follow-up support.</p></details></article>)}</div></div></section>

  <section className="qm-section qm-packages-section" id="qm-packages"><div className="qm-container"><div className="qm-heading centered qm-reveal"><p className="qm-kicker">CLEAR STARTING OPTIONS</p><h2>CHOOSE YOUR <em>GROWTH START.</em></h2><p>Final scope is confirmed after understanding your venue, location and current digital presence.</p></div><div className="qm-packages"><article className="qm-package"><small>ONE-TIME START</small><h3>Hospitality Growth Setup</h3><strong>₹9,999</strong><p>Audit, digital setup direction and automation consultation.</p><ul>{["Complete digital presence audit","Google and social profile review","Swiggy / Zomato listing review","Competitor observation","30-day growth roadmap","WhatsApp automation consultation"].map(x=><li key={x}>✓ {x}</li>)}</ul><a className="qm-button qm-button-dark" href="#qm-audit">START WITH AUDIT →</a></article><article className="qm-package featured"><small>SPECIAL MONTHLY OFFER</small><h3>Hospitality Growth Management</h3><strong>₹15,000 <del>₹20,000</del></strong><p>Consistent marketing support for visibility, content and campaigns.</p><ul>{["Facebook & Instagram management","12–15 posts per month","2–3 carousels per week","10 reels per month","Meta & Google Ads management","Google Business support","One planned interior content shoot","Monthly performance review"].map(x=><li key={x}>✓ {x}</li>)}</ul><QuicklyMediaWhatsApp className="qm-button qm-button-primary" placement="package">DISCUSS MONTHLY PLAN →</QuicklyMediaWhatsApp></article><article className="qm-package"><small>CUSTOM SYSTEM</small><h3>CRM & Automation</h3><strong>Custom</strong><p>Build a connected enquiry, booking and follow-up workflow.</p><ul>{["WhatsApp enquiry automation","Table booking workflow","Lead status and reminders","Customer database structure","Review request automation","Custom reporting dashboard"].map(x=><li key={x}>✓ {x}</li>)}</ul><QuicklyMediaWhatsApp className="qm-button qm-button-dark" placement="automation_package">REQUEST SCOPE →</QuicklyMediaWhatsApp></article></div><p className="qm-package-note">One month advance required for monthly management. Advertising, platform and promotional budgets are separate. Content-shoot logistics depend on location and finalized scope.</p></div></section>

  <section className="qm-section qm-audit" id="qm-audit"><div className="qm-container qm-audit-grid"><div className="qm-audit-copy qm-reveal"><p className="qm-kicker">FREE HOSPITALITY GROWTH AUDIT</p><h2>WHY ARE YOUR TABLES <em>NOT FULL?</em></h2><p>Let’s identify the visibility, offer, reservation or follow-up gap before you spend more.</p><div>{["Instagram & Facebook Review","Google Visibility Check","Website / Menu Review","Swiggy & Zomato Presence","Competitor Observation","Ads & Reservation Opportunity","Growth Recommendations"].map(x=><span key={x}>✓ {x}</span>)}</div><img src="/images/growth/lambodar-channel-growth.png" alt="Lambodar Patra with connected hospitality growth channels" loading="lazy"/></div><QuicklyMediaLeadForm/></div></section>

  <section className="qm-section qm-next"><div className="qm-container"><div className="qm-heading centered qm-reveal"><p className="qm-kicker">WHAT HAPPENS NEXT?</p><h2>A SIMPLE START. <em>CLEAR DIRECTION.</em></h2></div><div className="qm-next-grid">{[["01","Submit Your Venue"],["02","I Review Your Presence"],["03","15-Minute Discussion"],["04","Get Your Growth Direction"]].map(([no,text])=><article className="qm-step" key={no}><span>{no}</span><strong>{text}</strong></article>)}</div></div></section>

  <section className="qm-section qm-about"><div className="qm-container qm-split"><div className="qm-about-photo"><img src="/images/growth/lambodar-strategist.png" alt="Lambodar Patra — Hospitality Growth Consultant" loading="lazy"/><span>STRATEGY → EXECUTION → GROWTH</span></div><div className="qm-reveal"><p className="qm-kicker">ABOUT THE CONSULTANT</p><h2>HI, I’M <em>LAMBODAR PATRA.</em></h2><h3>Hospitality Growth & Digital Marketing Consultant</h3><p>With 8+ years of digital marketing and business-growth experience, I help hospitality businesses connect branding, performance marketing, local discovery, reservations and technology around a real commercial objective.</p><p>I don’t believe in selling the same social media package to every venue. The strategy should reflect your location, audience, offer, capacity and current growth challenge.</p><QuicklyMediaWhatsApp className="qm-button qm-button-primary" placement="about">LET’S DISCUSS YOUR VENUE →</QuicklyMediaWhatsApp></div></div></section>

  <section className="qm-section qm-faq"><div className="qm-container"><div className="qm-heading centered qm-reveal"><p className="qm-kicker">QUESTIONS, ANSWERED</p><h2>BEFORE WE <em>GET STARTED.</em></h2></div><div className="qm-faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>

  <section className="qm-final"><div className="qm-container qm-final-grid"><div><p className="qm-kicker">YOUR NEXT GROWTH MOVE</p><h2>YOUR TABLES SHOULD NOT <em>STAY EMPTY.</em></h2><p>Let’s build a connected system for visibility, enquiries, reservations and repeat customers.</p><div className="qm-actions"><a className="qm-button qm-button-primary" href="#qm-audit">GET FREE RESTAURANT GROWTH AUDIT</a><QuicklyMediaWhatsApp className="qm-button qm-button-whatsapp" placement="final">TALK TO LAMBODAR</QuicklyMediaWhatsApp></div><small>Free Initial Audit · Direct Discussion · No Obligation</small></div><img src="/images/growth/lambodar-fullbody.png" alt="Talk to Lambodar Patra about hospitality growth" loading="lazy"/></div></section>
  <footer className="qm-footer"><a className="qm-brand" href="#qm-top"><span>QUICKLY</span><b>MEDIA</b><small>Social Media Solutions for Hospitality</small></a><p>Restaurant · Cafe · Lounge · Club · Bar · Banquet Growth</p><div><a href="tel:+918128729003">+91 81287 29003</a><a href="mailto:connect@mydigitalskills.in">connect@mydigitalskills.in</a></div><small>© {new Date().getFullYear()} QuicklyMedia · A hospitality growth initiative by Lambodar Patra</small></footer>
  <div className="qm-mobile-bar"><QuicklyMediaWhatsApp placement="mobile_bar">WhatsApp</QuicklyMediaWhatsApp><a href="#qm-audit">Free Audit</a></div>
</main>}
